name: Code Analysis

on:
  pull_request:
  push:
  schedule:
    # Run Monday morning at 3 o'clock
    - cron: 0 3 * * 0
  workflow_dispatch:

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-20.04
    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      # Remove unnecessary dependencies not needed in this context
      - run: composer remove --dev friendsofphp/php-cs-fixer --no-update
      - run: composer remove --dev matt-allan/laravel-code-style --no-update

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - run: composer update --prefer-dist --no-progress

      - run: composer phpstan -- --no-progress

  code-style-checker:
    name: Code Style checker
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - run: composer update --prefer-dist --no-progress

      - run: composer lint
